apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: test-0923
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.0
        ports:
          - containerPort: 3000
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_AUTH_DISABLE_LOGIN_FORM
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: test-0923
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000