apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: test-0923
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args:
          - start
          - "--proxy=edge"  # Reverse proxy 설정
        env:
          - name: KEYCLOAK_ADMIN
            value: admin  # 관리자 계정 ID
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: admin  # 관리자 계정 비밀번호
          - name: KC_HOSTNAME
            value: keycloak.ghtjr.com  # Keycloak의 외부 도메인
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: test-0923
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080